apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      imagePullSecrets:
      - name: my-docker-credentials
      containers:
        image: imranathumber/hello-web:latest
        name: sample-app
        ports:
        - containerPort: 80
